In [14]:
import pandas as pd

In [15]:
df = pd.read_csv('GroceryStoreDataSet.csv', names=['products'], header = None)

In [16]:
df

                          products
0               MILK,BREAD,BISCUIT
1    BREAD,MILK,BISCUIT,CORNFLAKES
2              BREAD,TEA,BOURNVITA
3             JAM,MAGGI,BREAD,MILK
4                MAGGI,TEA,BISCUIT
5              BREAD,TEA,BOURNVITA
6             MAGGI,TEA,CORNFLAKES
7          MAGGI,BREAD,TEA,BISCUIT
8              JAM,MAGGI,BREAD,TEA
9                       BREAD,MILK
10  COFFEE,COCK,BISCUIT,CORNFLAKES
11  COFFEE,COCK,BISCUIT,CORNFLAKES
12          COFFEE,SUGER,BOURNVITA
13               BREAD,COFFEE,COCK
14             BREAD,SUGER,BISCUIT
15         COFFEE,SUGER,CORNFLAKES
16           BREAD,SUGER,BOURNVITA
17              BREAD,COFFEE,SUGER
18              BREAD,COFFEE,SUGER
19      TEA,MILK,COFFEE,CORNFLAKES

In [17]:
df.columns

Index(['products'], dtype='object')

In [18]:
df.values

array([['MILK,BREAD,BISCUIT'],
       ['BREAD,MILK,BISCUIT,CORNFLAKES'],
       ['BREAD,TEA,BOURNVITA'],
       ['JAM,MAGGI,BREAD,MILK'],
       ['MAGGI,TEA,BISCUIT'],
       ['BREAD,TEA,BOURNVITA'],
       ['MAGGI,TEA,CORNFLAKES'],
       ['MAGGI,BREAD,TEA,BISCUIT'],
       ['JAM,MAGGI,BREAD,TEA'],
       ['BREAD,MILK'],
       ['COFFEE,COCK,BISCUIT,CORNFLAKES'],
       ['COFFEE,COCK,BISCUIT,CORNFLAKES'],
       ['COFFEE,SUGER,BOURNVITA'],
       ['BREAD,COFFEE,COCK'],
       ['BREAD,SUGER,BISCUIT'],
       ['COFFEE,SUGER,CORNFLAKES'],
       ['BREAD,SUGER,BOURNVITA'],
       ['BREAD,COFFEE,SUGER'],
       ['BREAD,COFFEE,SUGER'],
       ['TEA,MILK,COFFEE,CORNFLAKES']], dtype=object)

In [19]:
data = list(df["products"].apply(lambda x:x.split(',')))
data

[['MILK', 'BREAD', 'BISCUIT'],
 ['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['JAM', 'MAGGI', 'BREAD', 'MILK'],
 ['MAGGI', 'TEA', 'BISCUIT'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['MAGGI', 'TEA', 'CORNFLAKES'],
 ['MAGGI', 'BREAD', 'TEA', 'BISCUIT'],
 ['JAM', 'MAGGI', 'BREAD', 'TEA'],
 ['BREAD', 'MILK'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'COCK'],
 ['BREAD', 'SUGER', 'BISCUIT'],
 ['COFFEE', 'SUGER', 'CORNFLAKES'],
 ['BREAD', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['TEA', 'MILK', 'COFFEE', 'CORNFLAKES']]

In [20]:
from mlxtend.preprocessing import TransactionEncoder

In [21]:
te = TransactionEncoder()
te_data = te.fit(data).transform(data)
df = pd.DataFrame(te_data, columns = te.columns_)
df

,BISCUIT,BOURNVITA,BREAD,COCK,COFFEE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,True,False,True,False,False,False,False,False,True,False,False
1,True,False,True,False,False,True,False,False,True,False,False
2,False,True,True,False,False,False,False,False,False,False,True
3,False,False,True,False,False,False,True,True,True,False,False
4,True,False,False,False,False,False,False,True,False,False,True
5,False,True,True,False,False,False,False,False,False,False,True
6,False,False,False,False,False,True,False,True,False,False,True
7,True,False,True,False,False,False,False,True,False,False,True
8,False,False,True,False,False,False,True,True,False,False,True
9,False,False,True,False,False,False,False,False,True,False,False
10,True,False,False,True,True,True,False,False,False,False,False
11,True,False,False,True,True,True,False,False,False,False,False
12,False,True,False,False,True,False,False,False,False,True,False
13,False,False,True,True,True,False,False,False,False,False,False
14,True,False,True,False,False,False,False,False,False,True,False
15,False,False,False,False,True,True,False,False,False,True,False
16,False,True,True,False,False,False,False,False,False,True,False
17,False,False,True,False,True,False,False,False,False,True,False
18,False,False,True,False,True,False,False,False,False,True,False
19,False,False,False,False,True,True,False,False,True,False,True

In [22]:
from mlxtend.frequent_patterns import apriori

In [23]:
df1 = apriori(df, min_support = 0.01, use_colnames = True)
df1

    support                             itemsets
0      0.35                            (BISCUIT)
1      0.20                          (BOURNVITA)
2      0.65                              (BREAD)
3      0.15                               (COCK)
4      0.40                             (COFFEE)
..      ...                                  ...
78     0.05         (MAGGI, TEA, BISCUIT, BREAD)
79     0.10  (BISCUIT, CORNFLAKES, COCK, COFFEE)
80     0.05            (MAGGI, JAM, MILK, BREAD)
81     0.05             (MAGGI, TEA, JAM, BREAD)
82     0.05      (TEA, MILK, CORNFLAKES, COFFEE)

[83 rows x 2 columns]

In [24]:
df1.sort_values(by = 'support', ascending = False)

    support                         itemsets
2      0.65                          (BREAD)
4      0.40                         (COFFEE)
0      0.35                        (BISCUIT)
10     0.35                            (TEA)
5      0.30                     (CORNFLAKES)
..      ...                              ...
55     0.05      (CORNFLAKES, BISCUIT, MILK)
57     0.05        (BREAD, SUGER, BOURNVITA)
17     0.05                 (SUGER, BISCUIT)
37     0.05              (MAGGI, CORNFLAKES)
82     0.05  (TEA, MILK, CORNFLAKES, COFFEE)

[83 rows x 2 columns]

In [25]:
df1['length'] = df1['itemsets'].apply(lambda x : len(x))
df1

    support                             itemsets  length
0      0.35                            (BISCUIT)       1
1      0.20                          (BOURNVITA)       1
2      0.65                              (BREAD)       1
3      0.15                               (COCK)       1
4      0.40                             (COFFEE)       1
..      ...                                  ...     ...
78     0.05         (MAGGI, TEA, BISCUIT, BREAD)       4
79     0.10  (BISCUIT, CORNFLAKES, COCK, COFFEE)       4
80     0.05            (MAGGI, JAM, MILK, BREAD)       4
81     0.05             (MAGGI, TEA, JAM, BREAD)       4
82     0.05      (TEA, MILK, CORNFLAKES, COFFEE)       4

[83 rows x 3 columns]

In [26]:
df1[(df1['length'] == 2) & (df1['support'] >= 0.05)]

    support               itemsets  length
11     0.20       (BISCUIT, BREAD)       2
12     0.10        (BISCUIT, COCK)       2
13     0.10      (BISCUIT, COFFEE)       2
14     0.15  (BISCUIT, CORNFLAKES)       2
15     0.10       (MAGGI, BISCUIT)       2
16     0.10        (BISCUIT, MILK)       2
17     0.05       (SUGER, BISCUIT)       2
18     0.10         (TEA, BISCUIT)       2
19     0.15     (BREAD, BOURNVITA)       2
20     0.05    (COFFEE, BOURNVITA)       2
21     0.10     (SUGER, BOURNVITA)       2
22     0.10       (TEA, BOURNVITA)       2
23     0.05          (COCK, BREAD)       2
24     0.15        (COFFEE, BREAD)       2
25     0.05    (CORNFLAKES, BREAD)       2
26     0.10           (JAM, BREAD)       2
27     0.15         (MAGGI, BREAD)       2
28     0.20          (MILK, BREAD)       2
29     0.20         (SUGER, BREAD)       2
30     0.20           (TEA, BREAD)       2
31     0.15         (COCK, COFFEE)       2
32     0.10     (CORNFLAKES, COCK)       2
33     0.20   (CORNFLAKES, COFFEE)       2
34     0.05         (MILK, COFFEE)       2
35     0.20        (SUGER, COFFEE)       2
36     0.05          (TEA, COFFEE)       2
37     0.05    (MAGGI, CORNFLAKES)       2
38     0.10     (CORNFLAKES, MILK)       2
39     0.05    (SUGER, CORNFLAKES)       2
40     0.10      (TEA, CORNFLAKES)       2
41     0.10           (MAGGI, JAM)       2
42     0.05            (JAM, MILK)       2
43     0.05             (TEA, JAM)       2
44     0.05          (MAGGI, MILK)       2
45     0.20           (MAGGI, TEA)       2
46     0.05            (TEA, MILK)       2